site_name: Tuscaloosa Area Black Chamber of Commerce
site_description: Connecting the disconnected.
site_url: http://www.tuscblackchamber.org
copyright: Copyright 2020, Tuscaloosa Area Black Chamber of Commerce

site_favicon: images/lightbulb/favicon.ico

# repository information
repo_url: https://github.com/almostengr/tabcc
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8080
  
extra_css: [css/extra.css]

# Appearance
theme:
  name: material
  # custom_dir: 'readthedocs'
  highlightjs: false
  language: en
  static_templates:
    - 404.html
    - 500.html
  include_search_page: true
  search_index_only: false
  highlightjs: false
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

use_directory_urls: true
strict: false

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra:
  generator: false