site_name: Tuscaloosa Area Black Chamber of Commerce
site_name_short: '<img src="/images/SmallLogo250x151.png" style="height: auto; width: 50px;" alt="TABCC Home">'
site_description: Connecting the disconnected.
site_url: http://www.tuscblackchamber.org
site_author: Tuscaloosa Area Black Chamber of Commerce (TABCC)
copyright: Tuscaloosa Area Black Chamber of Commerce (TABCC)

# repository information
repo_url: https://github.com/almostengr/tabcc
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 10.10.10.102:8080

# Appearance
theme:
  name: null
  custom_dir: 'theme'
  language: en
  # google_tag:
  site_icon: "/images/SmallLogo250x151.png"
  main:
    bgcolor: bg-white
  static_templates:
    - 404.html
    - 500.html
    - contact.php
  # sitemessage:
  #   - heading: ""
  #     detail: '<div class="text-center"><img src="/images/headerlogo.jpg" alt="TABCC logo and motto - TABCC, Connecting the Disconnected" ></div>'
  #     bgcolor: bg-white
  #     textcolor: text-black
  # homemessage:
  #   - heading: heading
  #     detail: detail
  #     bgcolor: bg-primary
  #     textcolor: text-light
  jumbotron:
    - heading: PROVIDING BUSINESS SUPPORT IN WEST ALABAMA
      detail: Need help starting a business? We help businesses get started and improve the community
      url: #
      background_image: "/images/blogpost-1.jpg"
      textcolor: text-white
      buttoncolor: btn-white
  mainnav:
    bgcolor: bg-yellow
    linkcolor: text-black
    buttoncolor: btn-yellow
    links:
    - url: /about
      name: ABOUT
      button: false
    - url: /membership
      name: MEMBERSHIP
      button: false
    - url: /resources
      name: RESOURCES
      button: false
    - url: https://www.facebook.com/tuscblackcc/events/
      name: EVENTS
      button: false
    - url: /jobs
      name: JOBS
      button: false
    - url: /contact.php
      name: CONTACT
      button: false
  featurette:
    - heading: 2025 Monthly Meetings
      description: We meet monthly on the 4th Thursday from 6-8PM at Cadence Bank, located at 2020 University Blvd, Tuscaloosa, Alabama. Please come out and join us.
      # buttonlink: /resources
      # buttontext: Find Out About Grants
      bgcolor: bg-white
      textcolor: text-black
      imageurl: /images/womenentrepreneur.jpg

    - heading: Small-Business Grants
      description: There are a number of small business grants that are available to small businesses. Find out more about these grants and to see if you qualify.
      buttonlink: /resources
      buttontext: Find Out About Grants
      bgcolor: bg-yellow
      textcolor: text-black
      imageurl: /images/one_dollar_bill.jpg
    - heading: Serving Tuscaloosa and Surrounding Communities
      description: We provide business support, networking, and financial resources.
      imageurl: /images/serving_tuscaloosa.jpg
      bgcolor: bg-white
      textcolor: text-black
      buttontext: Learn more about TABCC
      buttonlink: /about
    - heading: Attention Business Owners!
      description: Do you currently have a business or are planning on establishing your business in the Tuscaloosa, Alabama, West Central Alabama, or Black Belt of Alabama regions? Then you should join the Tuscaloosa Area Black Chamber of Commerce for resources and information that are only provided to members and partners. TABCC constantly developing programs and new initiatives that will help TABCC businesses move forward.
      imageurl: /images/womenentrepreneur.jpg
      bgcolor: bg-yellow
      textcolor: text-black
      buttontext: Become A Member!
  # promotions:
  #   - heading: Attention Business Owners!
  #     detail: Do you currently have a business or are planning on establishing your business in the Tuscaloosa, Alabama, West Central Alabama, or Black Belt of Alabama regions? Then you should join the Tuscaloosa Area Black Chamber of Commerce for resources and information that are only provided to members and partners. TABCC constantly developing programs and new initiatives that will help TABCC businesses move forward.
  #     buttoncolor: btn-dark-gray
  #     buttontext: Join Today!
  #     buttonlink: /membership
  #     bgcolor: bg-yellow
  #     textcolor: text-black
  subfooter:
    - bgcolor: bg-dark
      textcolor: text-white
      headercolor: text-yellow
      columns:
      - heading: Connect With TABCC!
        links:
        - name: Facebook
          url: "https://www.facebook.com/tuscblackcc"
          icon: bi bi-facebook
        - name: Twitter
          url: "https://twitter.com/tuscblackcc"
          icon: bi bi-twitter-x
      - heading: Affiliate Links
        links:
        - name: Alabama State Black Chamber of Commerce
          url: "http://www.alblackcc.org/"
          icon: bi-briefcase-fill
        - name: Birmingham Metro Black Chamber of Commerce
          url: "https://www.birminghammetrobcc.com/"
          icon: bi-briefcase-fill
        - name: East Alabama Black Chamber of Commerce
          url: "https://eabcc.org/"
          icon: bi-briefcase-fill
        - name: Huntsville Black Chamber of Commerce
          url: "http://hsvblackchamber.org"
          icon: bi-briefcase-fill
        - name: Mobile Area Black Chamber of Commerce
          url: "https://mabcc.org/"
          icon: bi-briefcase-fill
        - name: Northeast Alabama Black Chamber of Commerce
          url: "https://www.facebook.com/neabcc/"
          icon: bi-briefcase-fill
        - name: Wiregrass Black Chamber of Commerce
          url: "https://wiregrassbcc.org/"
          icon: bi-briefcase-fill
      - heading: "Other Links"
        links:
        - name: Contact
          url: /contact.php
          icon: bi bi-person-rolodex
        - name: 205-614-8585
          url: tel:205-614-8585
          icon: bi bi-telephone-fill
        - url:  "https://www.facebook.com/tuscblackcc/photos"
          name: Photos
          icon: bi bi-camera
        - url: /jobs
          name: Job Opportunities
          icon: bi bi-buildings-fill
        - url: /
          name: tuscblackchamber.org
          icon: bi bi-globe
        - url: /privacy
          name: Privacy Policy
          icon: bi bi-shield-lock-fill
  footer:
    - bgcolor: bg-black
      textcolor: text-yellow
      # links:
      # - url: "linkurl"
      #   name: "linkname"

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true

extra:
  generator: false
