name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pip
      run:  /usr/bin/python3 -m pip install --upgrade pip

    - name: Install setuptools
      run:  /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Install Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - run: git fetch -p

    - name: Build website
      run:  /usr/bin/python3 -m mkdocs build -f website/mkdocs.yml -d ../public

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUSCBLACKCHAMBER_778CA }}
        channelId: live
        projectId: tuscblackchamber-778ca
