name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pip
      run:  /usr/bin/python3 -m pip install --upgrade pip

    - name: Install setuptools
      run:  /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Install Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - name: Install Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs-rss-plugin

    - run: git fetch -p

    - name: Deploy to website branch
      run:  /usr/bin/python3 -m mkdocs gh-deploy -b website

  deploy:
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - name: Deploy to Production
      uses: fifsky/ssh-action@master
      with:
        command: cd && cd www && git pull origin website
        host: ${{ secrets.HOSTNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT_NUMBER }}
        user: ${{ secrets.USERNAME }}